name: Generate GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_lines: yes
          config_timezone: Asia/Kolkata
          config_display: large
          config_order: base.header, isocalendar, languages, achievements, habits
